-- Demo data for customer presentations (loaded only with the `demo` profile).
-- Kraków drone-strike scenario matches web-version.png; MED and MIL show triple use.
-- Alarm key epochs are generated by the backend on first start (no private keys in git).

-- ───────────── Organizations ─────────────
INSERT INTO organization (id, name, domain, parent_id) VALUES
    ('0a000000-0000-0000-0000-000000000001', 'Kraków City Crisis Management', 'CIV', NULL),
    ('0a000000-0000-0000-0000-000000000002', 'Primary School No. 5, Kraków',  'CIV', '0a000000-0000-0000-0000-000000000001'),
    ('0a000000-0000-0000-0000-000000000003', 'University Hospital — Emergency Department', 'MED', NULL),
    ('0a000000-0000-0000-0000-000000000004', 'Territorial Defence Company A', 'MIL', NULL);

-- ───────────── People ─────────────
INSERT INTO person (id, organization_id, display_name, role, phone) VALUES
    ('0b000000-0000-0000-0000-000000001001', '0a000000-0000-0000-0000-000000000001', 'Katarzyna Nowak',     'Crisis duty officer',          '+48 600 100 001'),
    ('0b000000-0000-0000-0000-000000003345', '0a000000-0000-0000-0000-000000000001', 'Tomasz Lewandowski',  'Liaison officer',              '+48 600 100 002'),
    ('0b000000-0000-0000-0000-000000043572', '0a000000-0000-0000-0000-000000000001', 'Ania Kowalska',       'Civil protection volunteer',   '+48 600 100 003'),
    ('0b000000-0000-0000-0000-000000005623', '0a000000-0000-0000-0000-000000000001', 'Maja Wiśniewska',     'Evacuation coordinator',       '+48 600 100 004'),
    ('0b000000-0000-0000-0000-000000009671', '0a000000-0000-0000-0000-000000000001', 'Jacek Zieliński',     'Civil protection volunteer',   '+48 600 100 005'),
    ('0b000000-0000-0000-0000-000000007710', '0a000000-0000-0000-0000-000000000002', 'Ewa Dąbrowska',       'School principal',             '+48 600 100 006'),
    ('0b000000-0000-0000-0000-000000011001', '0a000000-0000-0000-0000-000000000003', 'Dr Robert Krawczyk',  'Head of Emergency Department', '+48 600 200 001'),
    ('0b000000-0000-0000-0000-000000011002', '0a000000-0000-0000-0000-000000000003', 'Dr Piotr Mazur',      'Anesthesiologist',             '+48 600 200 002'),
    ('0b000000-0000-0000-0000-000000011003', '0a000000-0000-0000-0000-000000000003', 'Dr Anna Wójcik',      'Surgeon',                      '+48 600 200 003'),
    ('0b000000-0000-0000-0000-000000011004', '0a000000-0000-0000-0000-000000000003', 'Marta Kamińska',      'Triage nurse',                 '+48 600 200 004'),
    ('0b000000-0000-0000-0000-000000011005', '0a000000-0000-0000-0000-000000000003', 'Zofia Szymańska',     'Triage nurse',                 '+48 600 200 005'),
    ('0b000000-0000-0000-0000-000000011006', '0a000000-0000-0000-0000-000000000003', 'Paweł Kaczmarek',     'Radiology technician',         '+48 600 200 006'),
    ('0b000000-0000-0000-0000-000000021001', '0a000000-0000-0000-0000-000000000004', 'Capt. Adam Grabowski','Company commander',            '+48 600 300 001'),
    ('0b000000-0000-0000-0000-000000021002', '0a000000-0000-0000-0000-000000000004', 'Sgt. Michał Piotrowski','Squad leader',               '+48 600 300 002'),
    ('0b000000-0000-0000-0000-000000021003', '0a000000-0000-0000-0000-000000000004', 'Pvt. Kamil Pawlak',   'Rifleman',                     '+48 600 300 003');

-- ───────────── Device classes ─────────────
INSERT INTO device_class (id, code, criticality, default_relay_mode, may_poll_bearers, may_report_position) VALUES
    (1, 'RESPONDER',     'NON_CRITICAL', 'RELAY',        '{INTERNET,CELLULAR,WIFI_DIRECT,BLE}', true),
    (2, 'CITIZEN_RELAY', 'NON_CRITICAL', 'RELAY',        '{INTERNET,WIFI_DIRECT,BLE}',          false),
    (3, 'MEDICAL_STAFF', 'CRITICAL',     'RECEIVE_ONLY', '{INTERNET,PAGING,WIFI_DIRECT}',       true),
    (4, 'SOLDIER',       'CRITICAL',     'RECEIVE_ONLY', '{PMR,LORA_P2P,INTERNET}',             true),
    (5, 'CONSOLE',       'CRITICAL',     'RECEIVE_ONLY', '{INTERNET}',                          false);

-- ───────────── Devices: one phone per person, consoles for operators ─────────────
INSERT INTO device (id, person_id, device_class_id, platform)
SELECT ('0c000000-0000-0000-0000-' || right(p.id::text, 12))::uuid, p.id,
       CASE o.domain WHEN 'CIV' THEN 1 WHEN 'MED' THEN 3 ELSE 4 END, 'ANDROID'
FROM person p JOIN organization o ON o.id = p.organization_id;

INSERT INTO device (id, person_id, device_class_id, platform) VALUES
    ('0c000000-0000-0000-0000-000009001001', '0b000000-0000-0000-0000-000000001001', 5, 'DESKTOP'),
    ('0c000000-0000-0000-0000-000009011001', '0b000000-0000-0000-0000-000000011001', 5, 'DESKTOP'),
    ('0c000000-0000-0000-0000-000009021001', '0b000000-0000-0000-0000-000000021001', 5, 'DESKTOP');

INSERT INTO device_bearer (device_id, bearer, priority, address)
SELECT d.id, b.bearer::bearer, b.priority, NULL
FROM device d JOIN device_class c ON c.id = d.device_class_id
CROSS JOIN LATERAL (VALUES
    ('INTERNET', 1, ARRAY['RESPONDER','MEDICAL_STAFF','CONSOLE','SOLDIER']),
    ('WIFI_DIRECT', 2, ARRAY['RESPONDER','MEDICAL_STAFF']),
    ('BLE', 3, ARRAY['RESPONDER']),
    ('PMR', 0, ARRAY['SOLDIER'])
) AS b(bearer, priority, classes)
WHERE c.code = ANY (b.classes);

INSERT INTO device_bearer (device_id, bearer, priority, address)
SELECT d.id, 'PAGING', 3, 'CAP-' || right(d.id::text, 5)
FROM device d WHERE d.device_class_id = 3;

-- Demo PSK per device: "demo-psk-<first name>" (consoles: "demo-psk-console-<first name>").
INSERT INTO prototype_hsm_secret (ref, secret)
SELECT 'psk/' || d.id,
       convert_to('demo-psk-' || CASE WHEN d.platform = 'DESKTOP' THEN 'console-' ELSE '' END ||
                  lower(translate(split_part(regexp_replace(p.display_name, '^(Dr|Capt\.|Sgt\.|Pvt\.) ', ''), ' ', 1),
                                  'ąćęłńóśźżĄĆĘŁŃÓŚŹŻ', 'acelnoszzACELNOSZZ')), 'UTF8')
FROM device d JOIN person p ON p.id = d.person_id;

INSERT INTO device_credential (device_id, psk_hsm_ref, valid_from)
SELECT d.id, 'psk/' || d.id, now() - interval '30 days' FROM device d;

-- ───────────── Locations ─────────────
INSERT INTO location (id, organization_id, name, geom, address) VALUES
    ('0d000000-0000-0000-0000-000000000001', '0a000000-0000-0000-0000-000000000001', 'Public shelter S-07 Grzegórzki', ST_SetSRID(ST_MakePoint(19.9555, 50.0605), 4326), 'ul. Grzegórzecka 24, Kraków'),
    ('0d000000-0000-0000-0000-000000000002', '0a000000-0000-0000-0000-000000000001', 'Public shelter S-12 Kazimierz',  ST_SetSRID(ST_MakePoint(19.9440, 50.0525), 4326), 'ul. Starowiślna 77, Kraków'),
    ('0d000000-0000-0000-0000-000000000003', '0a000000-0000-0000-0000-000000000001', 'Evacuation point Wawel',         ST_SetSRID(ST_MakePoint(19.9318, 50.0535), 4326), 'Bulwar Czerwieński, Kraków'),
    ('0d000000-0000-0000-0000-000000000004', '0a000000-0000-0000-0000-000000000001', 'City Crisis Management Centre',  ST_SetSRID(ST_MakePoint(19.9478, 50.0452), 4326), 'Podgórze, Kraków'),
    ('0d000000-0000-0000-0000-000000000005', '0a000000-0000-0000-0000-000000000002', 'Primary School No. 5',           ST_SetSRID(ST_MakePoint(19.9270, 50.0690), 4326), 'ul. Szkolna 5, Kraków'),
    ('0d000000-0000-0000-0000-000000000006', '0a000000-0000-0000-0000-000000000003', 'Emergency Department',           ST_SetSRID(ST_MakePoint(20.0010, 50.0128), 4326), 'Building A, ground floor'),
    ('0d000000-0000-0000-0000-000000000007', '0a000000-0000-0000-0000-000000000003', 'Operating theatre block',        ST_SetSRID(ST_MakePoint(20.0024, 50.0133), 4326), 'Building B, 2nd floor'),
    ('0d000000-0000-0000-0000-000000000008', '0a000000-0000-0000-0000-000000000003', 'Triage area — ambulance bay',    ST_SetSRID(ST_MakePoint(20.0003, 50.0123), 4326), 'Building A, ambulance entrance'),
    ('0d000000-0000-0000-0000-000000000009', '0a000000-0000-0000-0000-000000000003', 'Imaging department',             ST_SetSRID(ST_MakePoint(20.0017, 50.0138), 4326), 'Building C, level -1'),
    ('0d000000-0000-0000-0000-000000000010', '0a000000-0000-0000-0000-000000000004', 'Equipment store',                ST_SetSRID(ST_MakePoint(19.8850, 50.0880), 4326), 'Garrison, building 3'),
    ('0d000000-0000-0000-0000-000000000011', '0a000000-0000-0000-0000-000000000004', 'Bunker B-2',                     ST_SetSRID(ST_MakePoint(19.8780, 50.0920), 4326), 'Sector North');

-- ───────────── Alarm definitions & scenario versions ─────────────
INSERT INTO alarm_definition (id, organization_id, code, name) VALUES
    ('0e000000-0000-0000-0000-000000000001', '0a000000-0000-0000-0000-000000000001', 'DRONE_STRIKE', 'Drone strike'),
    ('0e000000-0000-0000-0000-000000000002', '0a000000-0000-0000-0000-000000000001', 'AIR_RAID',     'Air raid'),
    ('0e000000-0000-0000-0000-000000000003', '0a000000-0000-0000-0000-000000000003', 'MCI_ED',       'Mass-casualty incident'),
    ('0e000000-0000-0000-0000-000000000004', '0a000000-0000-0000-0000-000000000004', 'MOBILIZATION', 'Mobilization');

-- Published bundles (object key + sha256) are produced by the backend on start.
INSERT INTO scenario_version (id, alarm_definition_id, version, status, published_at) VALUES
    ('0f000000-0000-0000-0000-000000000001', '0e000000-0000-0000-0000-000000000001', 1, 'PUBLISHED', now() - interval '7 days'),
    ('0f000000-0000-0000-0000-000000000002', '0e000000-0000-0000-0000-000000000002', 1, 'PUBLISHED', now() - interval '7 days'),
    ('0f000000-0000-0000-0000-000000000003', '0e000000-0000-0000-0000-000000000003', 1, 'PUBLISHED', now() - interval '7 days'),
    ('0f000000-0000-0000-0000-000000000004', '0e000000-0000-0000-0000-000000000004', 1, 'PUBLISHED', now() - interval '7 days');

UPDATE alarm_definition SET current_scenario_version_id = ('0f' || substr(id::text, 3))::uuid;

-- Relay override: during a drone strike medical phones also relay.
INSERT INTO relay_policy_override (scenario_version_id, device_class_id, relay_mode) VALUES
    ('0f000000-0000-0000-0000-000000000001', 3, 'RELAY');

-- ───────────── Task groups ─────────────
INSERT INTO task_group (id, scenario_version_id, name, location_id, order_no) VALUES
    -- Drone strike (Kraków)
    ('1a000000-0000-0000-0000-000000000001', '0f000000-0000-0000-0000-000000000001', 'Securing shelter',   '0d000000-0000-0000-0000-000000000001', 1),
    ('1a000000-0000-0000-0000-000000000002', '0f000000-0000-0000-0000-000000000001', 'Securing shelter',   '0d000000-0000-0000-0000-000000000002', 2),
    ('1a000000-0000-0000-0000-000000000003', '0f000000-0000-0000-0000-000000000001', 'Manage evacuation',  '0d000000-0000-0000-0000-000000000003', 3),
    ('1a000000-0000-0000-0000-000000000004', '0f000000-0000-0000-0000-000000000001', 'Notify authorities', '0d000000-0000-0000-0000-000000000004', 4),
    -- Air raid (Kraków)
    ('1a000000-0000-0000-0000-000000000005', '0f000000-0000-0000-0000-000000000002', 'Prepare school as shelter', '0d000000-0000-0000-0000-000000000005', 1),
    ('1a000000-0000-0000-0000-000000000006', '0f000000-0000-0000-0000-000000000002', 'Securing shelter',   '0d000000-0000-0000-0000-000000000001', 2),
    ('1a000000-0000-0000-0000-000000000007', '0f000000-0000-0000-0000-000000000002', 'Securing shelter',   '0d000000-0000-0000-0000-000000000002', 3),
    ('1a000000-0000-0000-0000-000000000008', '0f000000-0000-0000-0000-000000000002', 'Notify authorities', '0d000000-0000-0000-0000-000000000004', 4),
    -- Mass-casualty incident (hospital)
    ('1a000000-0000-0000-0000-000000000009', '0f000000-0000-0000-0000-000000000003', 'Anesthesia',         '0d000000-0000-0000-0000-000000000006', 1),
    ('1a000000-0000-0000-0000-000000000010', '0f000000-0000-0000-0000-000000000003', 'Surgery',            '0d000000-0000-0000-0000-000000000007', 2),
    ('1a000000-0000-0000-0000-000000000011', '0f000000-0000-0000-0000-000000000003', 'Triage',             '0d000000-0000-0000-0000-000000000008', 3),
    ('1a000000-0000-0000-0000-000000000012', '0f000000-0000-0000-0000-000000000003', 'Imaging',            '0d000000-0000-0000-0000-000000000009', 4),
    -- Mobilization (military)
    ('1a000000-0000-0000-0000-000000000013', '0f000000-0000-0000-0000-000000000004', 'Draw equipment',     '0d000000-0000-0000-0000-000000000010', 1),
    ('1a000000-0000-0000-0000-000000000014', '0f000000-0000-0000-0000-000000000004', 'Guard post',         '0d000000-0000-0000-0000-000000000011', 2);

-- ───────────── Tasks ─────────────
INSERT INTO task (task_group_id, order_no, description, requires_confirmation)
SELECT ('1a000000-0000-0000-0000-' || lpad(t.g::text, 12, '0'))::uuid, t.n, t.d, t.c
FROM (VALUES
    (1, 1, 'Go to public shelter S-07', false),
    (1, 2, 'Unlock the shelter, switch on lights and ventilation', false),
    (1, 3, 'Admit civilians and keep a headcount', true),
    (1, 4, 'Report shelter status to the crisis centre', true),
    (2, 1, 'Go to public shelter S-12', false),
    (2, 2, 'Unlock the shelter, switch on lights and ventilation', false),
    (2, 3, 'Admit civilians and keep a headcount', true),
    (2, 4, 'Report shelter status to the crisis centre', true),
    (3, 1, 'Go to the evacuation point at Wawel', false),
    (3, 2, 'Direct people away from the affected area', false),
    (3, 3, 'Coordinate buses with public transport dispatch', false),
    (3, 4, 'Report the number of evacuees', true),
    (4, 1, 'Go to the City Crisis Management Centre', false),
    (4, 2, 'Confirm the alarm with the Voivodeship Crisis Centre', true),
    (4, 3, 'Notify police, fire service and ambulance dispatch', false),
    (4, 4, 'Request a public cell-broadcast warning', true),
    (5, 1, 'Go to the school', false),
    (5, 2, 'Open the building', false),
    (5, 3, 'Open the shelter', false),
    (5, 4, 'Display required signs', true),
    (6, 1, 'Go to public shelter S-07', false),
    (6, 2, 'Open the shelter and admit civilians', true),
    (7, 1, 'Go to public shelter S-12', false),
    (7, 2, 'Open the shelter and admit civilians', true),
    (8, 1, 'Go to the City Crisis Management Centre', false),
    (8, 2, 'Confirm the alarm with the Voivodeship Crisis Centre', true),
    (9, 1, 'Report to the Emergency Department', false),
    (9, 2, 'Prepare airway and resuscitation stations', true),
    (10, 1, 'Go to the operating theatre', false),
    (10, 2, 'Prepare two operating rooms for trauma', true),
    (11, 1, 'Go to the triage area', false),
    (11, 2, 'Set up START triage zones and tags', false),
    (11, 3, 'Report casualty count every 15 minutes', true),
    (12, 1, 'Go to the imaging department', false),
    (12, 2, 'Clear the CT scanner for trauma patients', true),
    (13, 1, 'Report to the equipment store', false),
    (13, 2, 'Collect personal equipment', false),
    (13, 3, 'Take ammunition', true),
    (14, 1, 'Go to bunker B-2', false),
    (14, 2, 'Take up guard position', true)
) AS t(g, n, d, c);

-- ───────────── Assignments ─────────────
INSERT INTO assignment (task_group_id, person_id, rank)
SELECT ('1a000000-0000-0000-0000-' || lpad(a.g::text, 12, '0'))::uuid,
       ('0b000000-0000-0000-0000-' || lpad(a.p::text, 12, '0'))::uuid, a.r
FROM (VALUES
    (1, 43572, 1), (2, 9671, 1), (3, 5623, 1), (4, 3345, 1),
    (5, 7710, 1), (6, 43572, 1), (7, 9671, 1), (8, 3345, 1),
    (9, 11002, 1), (10, 11003, 1), (11, 11004, 1), (11, 11005, 2), (12, 11006, 1),
    (13, 21002, 1), (13, 21003, 1), (14, 21002, 1), (14, 21003, 1)
) AS a(g, p, r);

-- ───────────── Alarm controllers ─────────────
INSERT INTO alarm_controller (person_id, alarm_definition_id, can_raise, can_cancel, granted_by) VALUES
    ('0b000000-0000-0000-0000-000000001001', '0e000000-0000-0000-0000-000000000001', true, true, NULL),
    ('0b000000-0000-0000-0000-000000001001', '0e000000-0000-0000-0000-000000000002', true, true, NULL),
    ('0b000000-0000-0000-0000-000000003345', '0e000000-0000-0000-0000-000000000001', true, true, '0b000000-0000-0000-0000-000000001001'),
    ('0b000000-0000-0000-0000-000000011001', '0e000000-0000-0000-0000-000000000003', true, true, NULL),
    ('0b000000-0000-0000-0000-000000021001', '0e000000-0000-0000-0000-000000000004', true, true, NULL);

-- ───────────── Operator accounts (password: siren) ─────────────
INSERT INTO operator_account (username, password_hash, person_id, console_device_id) VALUES
    ('admin',    crypt('siren', gen_salt('bf', 10)), '0b000000-0000-0000-0000-000000001001', '0c000000-0000-0000-0000-000009001001'),
    ('hospital', crypt('siren', gen_salt('bf', 10)), '0b000000-0000-0000-0000-000000011001', '0c000000-0000-0000-0000-000009011001'),
    ('army',     crypt('siren', gen_salt('bf', 10)), '0b000000-0000-0000-0000-000000021001', '0c000000-0000-0000-0000-000009021001');

-- ───────────── Simulated responders (everyone except Tomasz, who is the live phone) ─────────────
INSERT INTO demo_simulated_device (device_id)
SELECT d.id FROM device d
WHERE d.platform = 'ANDROID'
  AND d.person_id NOT IN ('0b000000-0000-0000-0000-000000003345',
                          '0b000000-0000-0000-0000-000000001001',
                          '0b000000-0000-0000-0000-000000011001',
                          '0b000000-0000-0000-0000-000000021001');
